version: '3.1'
services:
  main-service:
    build: ./service
    restart: on-failure
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/film
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=film
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
